### ISSUE TITLE
Concrete annotations

### ISSUE THREAD

**Issue by marcioAlmada** [marcioAlmada/annotations#18]
Concrete annotations are annotations that map to concrete classes. Ex:

``` php
<?php
/**
 * @Entity ->
 * @InheritanceType -> "JOINED"
 * @DiscriminatorColumn -> {"name" : "desc", "type" : "string"}
 * @DiscriminatorMap -> {"person" : "Person", "employee" : "Employee"}
 */
```

Spec:
- Concrete type is defined by `->` symbol
- Syntax should look like this `@Annotation -> {valid json}`
- Parameters must be only a valid json string
- Namespaces should be supported `@App\Annotation`
- Concrete class must exist otherwise an exception is throw

Constraints:
- This functionality should not break backwards compatibility

**Comment by rulatir** [comment]
Sropping `[]` as syntactic sugar for constructor invocation is a disappointment :(

**Comment by marcioAlmada** [comment]
@rulatir See the commit above.

I've been thinking about allowing `-> []` as sugar for construct injection recently due to similar complaints. The good thing is that it won't be a BC break to allow it now.
