### ISSUE TITLE
Support for Doctrine style concrete annotations

### ISSUE THREAD

**Issue by thewunder** [marcioAlmada/annotations#43]
The majority of php annotation frameworks are based on doctrine/annotations.  They support class based annotations only, with constructor, property and setter based data injection in the following format:

@Class("constructor param", "constructor param 2")
@Class(propertyOne = "value one", propertyTwo = "value two")

In order to allow migration from other frameworks, this syntax should be supported.

**Comment by marcioAlmada** [comment]
Not really enough interest here so I'm closing the issue for now ^^
