### ISSUE TITLE
PHP7 support

### ISSUE THREAD

**Issue by marcioAlmada** [marcioAlmada/annotations#54]
Internal `Types\*` classes were renamed due to PHP7 bc breaks.

It's prudent to do a major release when first `php7-RC` arrives: https://github.com/marcioAlmada/annotations/commit/8cf541d7a0d6079ad320423da4c4b3fada69a353, https://github.com/marcioAlmada/annotations/commit/558b0e646c7b5804261a89bf9c9a236021acd4fb, https://github.com/marcioAlmada/annotations/commit/7d7c489b768ee4571bdf468c771271ab5a9433e0

**Comment by ValeriyMaslenikov** [comment]
Hi there, are there any updates about releasing version 3.0?

**Comment by marcioAlmada** [comment]
Hi, version [3.0.0](https://github.com/marcioAlmada/annotations/releases/tag/3.0.0) was just released.
