### ISSUE TITLE
Issue with space

### ISSUE THREAD

**Issue by gsouf** [marcioAlmada/annotations#55]
Hi,
Just got an issue while parsing annotation when the line following the annotation does not have a whitespace after the star character : 

php code : 

```php
$annotations = $reader->getClassAnnotations("someClass");
$foundTypes = $annotations->getAsArray("name");
```
Annotation with a white space (working as expected) :
```
/**
 * @name value
 *[WHITESPACE HERE]
 */

output > "value"
```

Annotation without a white space (issue) :
```
/**
 * @name value
 *[NO whitespace]
 */

output > "value
/"
```

**Comment by marcioAlmada** [comment]
Fixed. Please point your deps to master while it's not released.

Thanks for your report.

**Comment by gsouf** [comment]
No it's ok for the master branch, I can deal with it in the interim 
Thank for the special mention https://github.com/marcioAlmada/annotations/commit/23455d0bd9e922e65ed8bfca89611b990e01a852#diff-d4c80072c47835582f6adbd85edb3782R236
:)
