### ISSUE TITLE
Is there a way to get constant annotation ?

### ISSUE THREAD

**Issue by gsouf** [marcioAlmada/annotations#56]
Hi, as says the tilte is there a way to get constant annotations ? As far as I cheked I didnt find such a feature.

**Comment by marcioAlmada** [comment]
We don't have that yet.

**Comment by marcioAlmada** [comment]
This would be very welcome.

**Comment by gsouf** [comment]
According to this answer, there is no builtin way to get the constant doc comment : http://stackoverflow.com/questions/22103019/php-reflection-get-constants-doc-comment

@marcioAlmada I'm not really experienced with that, what do you think of the usage of ``token_get_all`` to get const doc comment ? 

That would be something like:

```
foreach token
   if token is doc comment
       if next token is constant
           then we have a constant doc comment
```

**Comment by marcioAlmada** [comment]
I think it's ok as long as we don't add any performance hit to the other methods :)

```
foreach tokens
   if token is T_CONSTANT
       if previous token is T_DOC_COMMENT
           then we have a constant doc comment
```

Just beware that the following syntax is also valid PHP:

```php
class Constants {
    const
        /** @var int */
        CONST_X = 1,
        /** @var int */
        CONST_Y = 2
    ;
}
```

With that said, I suggest you to see if https://github.com/nikic/PHP-Parser supports visiting constant's docblock nodes in some way first.

**Comment by gsouf** [comment]
I tested the following code: 

```php

        $parser = new Parser(new Lexer());
        $stmts = $parser->parse("

        <?php

        class SomeClass {

             /**
              * @someAnnotation
              */
             const SOME_CONSTANT = 'some value';


             const
                 /**
                  * @someAnnotation
                  */
                 FOO = 'some value',
                 /**
                  * @someAnnotation
                  */
                 BAR = 'some value';


        }

        ");
```


And ``nikic/php-parser `` is able to parse the two syntaxes with doc comments.

Do you want to use ``nikic/php-parser`` as a dependency ?

**Comment by gsouf** [comment]
Ok, we have an additional edge case. I'd like to know how you want to treat it.


What's about this syntax: 

Case 1
```php
 
/**
 * @global
 */
const 
         FOO =  "foo",
         BAR = "bar";
```

Case 2
```php
 
/**
 * @global
 */
const 
         /**
          * @foo
          */
         FOO =  "foo",
         /**
          * @bar
          */
         BAR = "bar";
```


Should ``@global`` be ignored or should it belong to both of FOO and BAR, in case 1 ? in case 2 ?

**Comment by gsouf** [comment]
Ok, one more question

What to do in these cases: 

Case 3
```php

/**
 * @annotation1
 */
/**
 * @annotation2
 */
const SOME_CONST = "...":

```

Case 4 
```php

/**
 * @annotation1
 */
// Some comment
const SOME_CONST = "...":

```

**Comment by marcioAlmada** [comment]
I think we should always get the closest docblock related to the constant name declaration. Also, docblocks should have a 1-1 relation to a declaration. The following example should be an unambiguous guide to all the cases: https://3v4l.org/XjKfG

**Comment by marcioAlmada** [comment]
On the 3val you will notice a different behavior between PHP 5 and 7, don't worry about that. We should mimic the PHP5. I'll see on internals if the PHP 7 behavior was intentional (it's probably a bug).

**Comment by gsouf** [comment]
Got it, I updated the tests and the code with the good standards
