### ISSUE TITLE
Upgrade to Nikic parser 2

### ISSUE THREAD

**Issue by rulatir** [marcioAlmada/annotations#62]
This package fixes the Nikic PHP parser dependency at 1.* which is ancient. Please upgrade!

**Comment by marcioAlmada** [comment]
Dependency has been updated and unit tests seem fine. Please point to master from now. A minor release will come soon if no problems arise.

**Comment by rulatir** [comment]
Seems to be working fine.

**Comment by thewunder** [comment]
Yes please release a 3.0.1, this is causing a version conflict with another package for me

**Comment by marcioAlmada** [comment]
Just released https://github.com/marcioAlmada/annotations/releases/tag/3.0.1

I apologize for the delay 😅
